---
openapi: 3.0.3
info:
  title: Fruits API
  version: "1.0"
  description: OpenAPI document for Fruits API
servers:
- url: http://localhost:8080/
  description: ""
paths:
  /fruits:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetFruit'
          description: OK
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fruit'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetFruit'
          description: OK
    delete:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetFruit'
          description: OK
components:
  schemas:
    Fruit:
      type: object
      properties:
        description:
          type: string
        name:
          type: string
    SetFruit:
      uniqueItems: true
      type: array
      items:
        $ref: '#/components/schemas/Fruit'
  securitySchemes:
    oidc:
      flows:
        clientCredentials:
          tokenUrl: https://sso.apps.jeannyil.sandbox1444.opentlc.com/auth/realms/RH3scaleAdminPortal/protocol/openid-connect/token
          scopes:
            openid: ""
        authorizationCode:
          authorizationUrl: https://sso.apps.jeannyil.sandbox1444.opentlc.com/auth/realms/RH3scaleAdminPortal/protocol/openid-connect/auth
          tokenUrl: https://sso.apps.jeannyil.sandbox1444.opentlc.com/auth/realms/RH3scaleAdminPortal/protocol/openid-connect/token
          refreshUrl: https://sso.apps.jeannyil.sandbox1444.opentlc.com/auth/realms/RH3scaleAdminPortal/protocol/openid-connect/token
          scopes:
            openid: ""
      type: oauth2
security:
- oidc:
  - openid
